# [[main]]
#   name = "Home"
#   url = ""
#   weight = -110

[[main]]
  name = "貼文"
  url = "post/"
  weight = -112

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Github"
  url = "https://github.com/stevengogogo"
[[main]]
  parent = "Links"
  name = "NTU mito Lab"
  url = "https://ntubmse.com/"

[[main]]
  name = "簡介"
  url = "about/"
  weight = -107